### ISSUE TITLE
Can't enter uppercase `S`!

### ISSUE THREAD

**Issue by gene-pavlovsky** [ianxm/ihx#12]
I've just installed `ihx` and tried to use it for the first time.
I was trying to enter `var str:String = 'hello world';` but strangely, when I press shift+S, nothing happend, `S` doesn't appear.
Moreover, it can't be pasted from clipboard either! When I tried the write to file example from the README, I pasted this line `fout.writeString("hello\n");`, but it appeared as `fout.writetring("hello\n");` and ihx then complained that there is no field `writetring`.
What's up with that?

**Comment by ianxm** [comment]
This is probably a keycode issue. Build the program below and run it and tell me what your system name is and what codes you have for "S" and control-d.

    import neko.Lib;

    /**
      print system name and keyboard scan codes as they're typed.
    **/
    class Keymap {
        public static function main() {
            Lib.println("system name: " + std.Sys.systemName());
            var code = 0;
            while (code != 3) { // ctrl-c to exit
                code = Sys.getChar(false);
                Lib.println("code: " + code);
            }
        }
    }

**Comment by ianxm** [comment]
this is a dup of #9.

**Comment by gene-pavlovsky** [comment]
I'll post to #9, then. Sorry for the dup.
