### ISSUE TITLE
Preserve History between ConsoleReader sessions

### ISSUE THREAD

**Issue by NQNStudios** [ianxm/ihx#17]
I've been working on a language in Haxe with a Repl and realized today that I can use your ConsoleReader class to get command history functionality. Which is awesome.

Since I'm debugging expressions in my language, then fiddling around with the interpreter, relaunching, and testing the same expression again, it would be nice if command history could be serialized to a dotfile. Right now History is a private variable in ConsoleReader that's constructed every time -- would you accept a PR that adds optional serialization/deserialization of a History object?

**Comment by ianxm** [comment]
Yes, that sounds fine.

How were you thinking of making it optional? Were you thinking of adding a
command line option to enable it?

Be careful not to tie the implementation to a particular platform.

**Comment by NQNStudios** [comment]
For the implementation, I'm thinking:

* Add optional parameters to ConsoleReader.new(): one is a file path for the persistent history file, the other is a maximum number of commands to store in that file
* At construction, if the the file path is provided, load the history list from that file
* When a command is saved to the history, also update the file
* Add command line options that can be passed to the ConsoleReader.new()

**Comment by ianxm** [comment]
that sounds good.

**Comment by ianxm** [comment]
pull request merged. thanks!
