### ISSUE TITLE
ConsoleReader depends on Neko

### ISSUE THREAD

**Issue by NQNStudios** [ianxm/ihx#18]
I want to use the ConsoleReader class to add up/down command history to my own Repl. I'm getting errors when I run my program: `You cannot access the neko package while targeting eval (for neko.Lib)`. I assume I can work around this by figuring out how to target Neko when my language is running its Repl, but I also looked into the ConsoleReader source and it looks like neko.Lib is only used for printing. Would it be better to use Sys for printing instead?

**Comment by ianxm** [comment]
Yeah that makes sense. I thought of ihx as a Neko app so it didn't occur to
me that the dependency would be a problem.

**Comment by ianxm** [comment]
removed neko.Lib dependency
