### ISSUE TITLE
First argument is ignored on Windows

### ISSUE THREAD

**Issue by NQNStudios** [ianxm/ihx#22]
On Windows running with Haxe 4, the first argument is dropped. If the first argument is followed by an input value, that input value will not be recognized as an argument, and IHx will not start.

Examples:
`haxelib run ihx -lib ihx`
`neko run.n -lib ihx`
Will both trigger the error.

I'm guessing in older Haxe versions, `Sys.args()` would come with an extra value on Windows? [Here](https://github.com/ianxm/ihx/blob/473ceafc7ca942b5973980255a812eaa1db17a3f/src/ihx/IHx.hx#L76) is the line of code causing the error, I assume it is there for a reason that doesn't need to be anymore.

**Comment by ianxm** [comment]
thanks for reporting. yeah, windows used to need that. I haven't used windows in a long time. if you send a PR I'll take it. I don't want to just take it out and push without being able to test.
