### ISSUE TITLE
History navigation broken in VSCode terminal on Windows

### ISSUE THREAD

**Issue by NQNStudios** [ianxm/ihx#23]
When running ihx in the VSCode terminal on Windows, the keys for navigating command history don't work. "up" inputs "H", and other oddities like that.

I thought it might be using a different code set, so I started running this command and testing what codes ihx is getting sent:
`trace(Sys.getChar(false));`

The weird thing is that Sys.getChar() does not always receive the first key I type. If I type "up" repeatedly, it will eventually return 72, the proper code for Windows.

Sometimes if I type keys repeatedly it will eventually return `0` instead of the code for the proper key.

It strikes me that this might be a VSCode bug, or a Haxe bug. But I wanted to write that all down somewhere for now.

**Comment by NQNStudios** [comment]
To complicate things, I am using an Msys terminal in VSCode, which might be bringing all these weird sorts of CygWIN/PuTTY bugs into the mix because it's also based on MinGW.

**Comment by NQNStudios** [comment]
Just tested a regular `cmd` prompt from inside visual studio code and the problem is still there. So it's probably a VSCode bug.

**Comment by ianxm** [comment]
I don't have a Windows machine to test on, and it's not clear that this is fixable, so I'm gonna close it. if you happen to figure it out and it's fixable please reopen. Thanks for reporting, though.
