### ISSUE TITLE
Run ihx in Python

### ISSUE THREAD

**Issue by NQNStudios** [ianxm/ihx#24]
In one of the issues I opened/commented on, @ianxm suggested it would be cool to have ihx portable to targets other than Neko. The more I think about it, I agree. The next time I have the time and inclination, I'd like to try contributing a Python version.

I'm thinking the ideal interface for running IHX with different targets would be a command line argument like `ihx -python` or `ihx -neko`.

**Comment by ianxm** [comment]
a little while after we talked about that I added -neko and -hl options and made the default run `haxe --interp`. it was easier than I expected. adding python might be easy as well.

**Comment by ianxm** [comment]
merged your pr, thanks!
