### ISSUE TITLE
Keyboard input in Windows

### ISSUE THREAD

**Issue by mknart** [ianxm/ihx#9]
Hey. I'm having some.. interesting problems. 

I can't type any Swedish characters (ÅÄÖåäö), which is less of a problem, but a bigger issue is the missing capital S. All other regular keys seem to work. Even when pasting text, capital S is excluded.

```
d:\> rem "This is a String"
d:\> haxelib run ihx
haxe interactive shell v0.3.4
type "help" for help
>> "This is a tring"
String : This is a tring

>>
```

Win7Pro64. Swedish keyboard layout.

**Comment by gene-pavlovsky** [comment]
On my system, uppercase S is 83, Ctrl+d is 4.
Additionally, I have a Cygwin environment that I prefer to use via [PuTTY+cygtermd](http://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/cygwin-terminal-window.html) - the Keymap test program doesn't catch any input and so doesn't produce any output. I didn't have problems with any other console programs so far.

**Comment by ianxm** [comment]
@gene-pavlovsky, the "no input" problem sounds like an issue with the neko standard library's Sys.getChar() method. I would need a cygwin environment to troubleshoot it. I recommend posting to the haxe mailing list that the program above produces no output in that environment.

The capital S issue should be fixable, though. What does `std.Sys.systemName()` return? When you run the keycode program, what are the arrow keys?

**Comment by gene-pavlovsky** [comment]
I think this is related to using PuTTY as the terminal emulator, not Cygwin itself.

If I run `neko KbInput.n` in the Windows console, input (up, down, left, right, ctrl+c):

```
c:\project>neko KbInput.n
Windows
Control-C to exit

got: 224

got: 72

got: 224

got: 80

got: 224

got: 75

got: 224

got: 77

got: 3
```

Starting Cygwin's bash, and doing the same - same result.

When running with PuTTY, though, either through ssh, or through local connection using cygtermd, arrows actually move the cursor up/down/left/right.

`systemName` returns `Windows` in all cases.

**Comment by ianxm** [comment]
I've changed the windows keycode for ctrl-d to what you're getting. the other windows control keys matched between linux and windows so that makes sense. hopefully that will fix it for windows terminal and cygwin's bash. try the latest and let me know.

open a new ticket for putty.

**Comment by gene-pavlovsky** [comment]
Before I open a new ticket, I want to report the following progress.
I was reading a forum topic about how to run `Far`, a console file manager for Windows, from Cygwin terminal (i.e. mintty), and a developer suggested trying `winpty`.
Following a hunch, I've installed `winpty`, and executed `winpty haxelib run ihx`. It worked - could receive input (and also unable to enter capital letter `S`).
So my question here, when built on Windows platform, neko lib relies on Windows console interface? Is there a way to target UNIX while building on Windows?

**Comment by ianxm** [comment]
is this the putty test? I'm not sure how the windows haxe binaries are built, but the wiki has [instructions](http://old.haxe.org/doc/build/haxe_windows) for building it using cygwin and mingw. You could try doing one of those builds and see if it helps. If you manage to build haxe for unix pty on windows it will probably stop working from the windows console.

Let me know if the capital `S` works with the latest version.

**Comment by gene-pavlovsky** [comment]
Yeah I think if I gain one thing I will lose another thing. Maybe I'll just add to my ~/.bashrc: `test "$TERM" != cygwin && alias ihx='winpty haxelib run ihx' || alias ihx='haxelib run ihx'`.
But running through `winpty` the arrows are messed up, printing H,K,P,M (up,left,down,right resp.) (KbInput returns same codes as H,K,P,M). Changing TERM or putty keyboard behavior options didn't change anything. Probably winpty-related, I'll try to research about that. 

I can enter capital `S` now, Ctrl+D works as well! Thanks :) I still have this issue:
Enter `var str:String = 'string'` (no semicolon), press enter. Repeat several times. Sometimes it prints back `String : text`, sometimes there is an empty line instead. This happens running on regular console or mintty+winpty, doesn't matter.

A minor thing is - when I'm typing, using left/right arrows to navigate within the current command, or using up/down arrows to move in history of commands, the caret is hidden all the time, until I stop pressing any keys, then the caret starts blinking again. Shouldn't the caret stay visible instead (I think that's what it does in other shells / text editors etc.)

**Comment by ianxm** [comment]
closing this. I think the remaining problem is tracked in another issue.
